version: 1.0.0
name: freezed_milliseconds_to_datetime_converter
description: Easily transform your int properties into DateTimes.

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  freezed_annotation: ^2.1.0
# dependencies:
#   path: ^1.8.0

# dev_dependencies:
#   lints: ^2.0.0
#   test: ^1.16.0
